# EV Charging Station Planning & Demand Prediction System

## Notebook 01: Data Loading

### Business Objective

The objective of this notebook is to load all raw datasets required for the project and perform an initial inspection of the data before preprocessing.

This notebook helps us understand the structure of each dataset, including the number of records, columns, data types, and overall dataset quality.

In [ ]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
c:\Users\admin\OneDrive\Desktop\simple project\EV-Charging-Demand-Prediction\notebooks

In [ ]:
stations_df = pd.read_csv("../data/raw/ev_charging_stations.csv")

usage_df = pd.read_csv("../data/raw/ev_charging_usage.csv")

registration_df = pd.read_csv("../data/raw/ev_registration_by_state.csv")

population_df = pd.read_csv("../data/raw/indian_cities_population.csv")

In [ ]:
print("="*60)
print("All datasets loaded successfully.")
print("="*60)

============================================================
All datasets loaded successfully.
============================================================

In [ ]:
print("EV Charging Stations :", stations_df.shape)
print("Charging Usage       :", usage_df.shape)
print("EV Registration      :", registration_df.shape)
print("Population           :", population_df.shape)

EV Charging Stations : (855, 9)
Charging Usage       : (500, 9)
EV Registration      : (32, 13)
Population           : (493, 22)

In [ ]:
summary = pd.DataFrame({

"Dataset":[
"EV Charging Stations",
"Charging Usage",
"EV Registration",
"Population"
],

"Rows":[
stations_df.shape[0],
usage_df.shape[0],
registration_df.shape[0],
population_df.shape[0]
],

"Columns":[
stations_df.shape[1],
usage_df.shape[1],
registration_df.shape[1],
population_df.shape[1]
]

})

summary

                Dataset  Rows  Columns
0  EV Charging Stations   855        9
1        Charging Usage   500        9
2       EV Registration    32       13
3            Population   493       22

In [ ]:
stations_df.head()

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
0,Tata.ev Luxon Motors - Tata Power,Edappally,Kerala,10.011485,76.311387,Tata Power,Public - Membership Required,CCS (Type 2),60.0
1,TML Sree Gokulam Motors - Tata Power,Edappally,Kerala,10.039155,76.315559,Tata Power,Public - Membership Required,CCS (Type 2),30.0
2,Tata.ev Gokulam Motors - Tata Power,Choornikkara,Kerala,10.081303,76.339462,Tata Power,Public - Membership Required,CCS (Type 2),60.0
3,Taj Cochin Internation Airport Hotel - Tata Power,Nedumbassery,Kerala,10.159995,76.390154,Tata Power,Public - Membership Required,CCS (Type 2),30.0
4,SAJ Earth Resort - Tata Power,Nedumbassery,Kerala,10.162224,76.384653,Tata Power,Public - Membership Required,CCS (Type 2),30.0

In [ ]:
usage_df.head()

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method
0,ST001,Kolkata,2025-10-15,Car,12:14,13:57,96.2,962.0,UPI
1,ST002,Pune,2025-10-15,Bus,15:27,17:26,59.2,592.0,UPI
2,ST003,Hyderabad,2025-10-15,Car,11:29,12:08,59.8,598.0,Cash
3,ST004,Indore,2025-10-15,Bus,10:12,11:45,38.3,383.0,Cash
4,ST005,Indore,2025-10-15,Car,10:19,11:03,48.9,489.0,Card

In [ ]:
registration_df.head()

,Unnamed: 0,State Name,Two Wheeler,Three Wheeler,Four Wheeler,Goods Vehicles,Public Service Vehicle,Special Category Vehicles,Ambulance/Hearses,Construction Equipment Vehicle,Other,Grand Total,total-charging-stations
0,0,Andaman and Nicobar Island,1,30.0,81,0.0,40.0,0.0,0.0,0.0,7.0,159,NaN
1,1,Arunachal Pradesh,14,0.0,5,0.0,0.0,0.0,0.0,0.0,1.0,20,NaN
2,2,Assam,721,47041.0,161,7.0,15.0,0.0,0.0,0.0,2.0,47947,10.0
3,3,Bihar,5003,59079.0,114,11.0,26.0,0.0,0.0,0.0,8.0,64241,9.0
4,4,Chandigarh,298,1410.0,182,0.0,40.0,0.0,0.0,0.0,1.0,1931,2.0

In [ ]:
population_df.head()

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,literates_total,literates_male,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
0,Abohar,3,PUNJAB,9,145238,76840,68398,15870,8587,7283,103319,58347,44972,890,848,79.86,85.49,73.59,"30.1452928,74.1993043",16287,8612,7675
1,Achalpur,27,MAHARASHTRA,7,112293,58256,54037,11810,6186,5624,92433,49347,43086,928,909,91.99,94.77,89.00,"21.257584,77.5086754",8863,5269,3594
2,Adilabad,28,ANDHRA PRADESH,1,117388,59232,58156,13103,6731,6372,83955,46295,37660,982,947,80.51,88.18,72.73,"19.0809075,79.560344",10565,6797,3768
3,Adityapur,20,JHARKHAND,24,173988,91495,82493,23042,12063,10979,125985,71470,54515,902,910,83.46,89.98,76.23,"22.7834741,86.1576889",19225,12189,7036
4,Adoni,28,ANDHRA PRADESH,21,166537,82743,83794,18406,9355,9051,101292,56203,45089,1013,968,68.38,76.58,60.33,"15.6322227,77.2728368",11902,7871,4031

In [ ]:
print(stations_df.columns.tolist())

['Station Name', 'City', 'State', 'Latitude', 'Longitude', 'Operator', 'Usage Type', 'Connector Type', 'Power (kW)']

In [ ]:
print(usage_df.columns.tolist())

['Station_ID', 'City', 'Date', 'Vehicle_Type', 'Charging_Start_Time', 'Charging_End_Time', 'Energy_Consumed_kWh', 'Cost_INR', 'Payment_Method']

In [ ]:
print(registration_df.columns.tolist())

['Unnamed: 0', 'State Name', 'Two Wheeler', 'Three Wheeler', 'Four Wheeler', 'Goods Vehicles', 'Public Service Vehicle', 'Special Category Vehicles', 'Ambulance/Hearses', 'Construction Equipment Vehicle', 'Other', 'Grand Total', 'total-charging-stations']

In [ ]:
print(population_df.columns.tolist())

['name_of_city', 'state_code', 'state_name', 'dist_code', 'population_total', 'population_male', 'population_female', '0-6_population_total', '0-6_population_male', '0-6_population_female', 'literates_total', 'literates_male', 'literates_female', 'sex_ratio', 'child_sex_ratio', 'effective_literacy_rate_total', 'effective_literacy_rate_male', 'effective_literacy_rate_female', 'location', 'total_graduates', 'male_graduates', 'female_graduates']

In [ ]:
stations_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 855 entries, 0 to 854
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Station Name    855 non-null    str
 1   City            855 non-null    str
 2   State           854 non-null    str
 3   Latitude        855 non-null    float64
 4   Longitude       855 non-null    float64
 5   Operator        855 non-null    str
 6   Usage Type      855 non-null    str
 7   Connector Type  855 non-null    str
 8   Power (kW)      853 non-null    float64
dtypes: float64(3), str(6)
memory usage: 141.1 KB

In [ ]:
usage_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Station_ID           500 non-null    str
 1   City                 500 non-null    str
 2   Date                 500 non-null    str
 3   Vehicle_Type         500 non-null    str
 4   Charging_Start_Time  500 non-null    str
 5   Charging_End_Time    500 non-null    str
 6   Energy_Consumed_kWh  500 non-null    float64
 7   Cost_INR             500 non-null    float64
 8   Payment_Method       500 non-null    str
dtypes: float64(2), str(7)
memory usage: 54.3 KB

In [ ]:
registration_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      32 non-null     int64
 1   State Name                      32 non-null     str
 2   Two Wheeler                     32 non-null     int64
 3   Three Wheeler                   32 non-null     float64
 4   Four Wheeler                    32 non-null     int64
 5   Goods Vehicles                  32 non-null     float64
 6   Public Service Vehicle          32 non-null     float64
 7   Special Category Vehicles       32 non-null     float64
 8   Ambulance/Hearses               32 non-null     float64
 9   Construction Equipment Vehicle  32 non-null     float64
 10  Other                           32 non-null     float64
 11  Grand Total                     32 non-null     int64
 12  total-charging-stations         24 non-null     float64
dtypes: float64(8), int64(4), str(1)
memory usage: 3.7 KB

In [ ]:
population_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name_of_city                    493 non-null    str
 1   state_code                      493 non-null    int64
 2   state_name                      493 non-null    str
 3   dist_code                       493 non-null    int64
 4   population_total                493 non-null    int64
 5   population_male                 493 non-null    int64
 6   population_female               493 non-null    int64
 7   0-6_population_total            493 non-null    int64
 8   0-6_population_male             493 non-null    int64
 9   0-6_population_female           493 non-null    int64
 10  literates_total                 493 non-null    int64
 11  literates_male                  493 non-null    int64
 12  literates_female                493 non-null    int64
 13  sex_ratio                       493 non-null    int64
 14  child_sex_ratio                 493 non-null    int64
 15  effective_literacy_rate_total   493 non-null    float64
 16  effective_literacy_rate_male    493 non-null    float64
 17  effective_literacy_rate_female  493 non-null    float64
 18  location                        493 non-null    str
 19  total_graduates                 493 non-null    int64
 20  male_graduates                  493 non-null    int64
 21  female_graduates                493 non-null    int64
dtypes: float64(3), int64(16), str(3)
memory usage: 103.9 KB

In [ ]:
stations_df.describe(include="all")

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
count,855,855,854,855.000000,855.000000,855,855,855,853.000000
unique,489,285,18,NaN,NaN,10,4,7,NaN
top,ChargeMOD EVCS Hub,Thiruvananthapuram,Kerala,NaN,NaN,ChargeMod (IN),Public - Membership Required,CCS (Type 2),NaN
freq,6,44,769,NaN,NaN,388,774,565,NaN
mean,NaN,NaN,NaN,10.503103,76.533179,NaN,NaN,NaN,30.569871
std,NaN,NaN,NaN,2.054603,1.129636,NaN,NaN,NaN,19.908080
min,NaN,NaN,NaN,8.306584,74.202737,NaN,NaN,NaN,3.200000
25%,NaN,NaN,NaN,9.551795,76.183041,NaN,NaN,NaN,22.000000
50%,NaN,NaN,NaN,10.197144,76.388294,NaN,NaN,NaN,30.000000
75%,NaN,NaN,NaN,11.058305,76.743625,NaN,NaN,NaN,30.000000
max,NaN,NaN,NaN,28.706612,88.456284,NaN,NaN,NaN,150.000000

In [ ]:
usage_df.describe(include="all")

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method
count,500,500,500,500,500,500,500.000000,500.00000,500
unique,500,10,1,4,384,386,NaN,NaN,3
top,ST001,Delhi,2025-10-15,Truck,08:14,18:54,NaN,NaN,Cash
freq,1,58,500,132,4,3,NaN,NaN,169
mean,NaN,NaN,NaN,NaN,NaN,NaN,52.680400,526.80400,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,27.589008,275.89008,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,32.00000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,28.650000,286.50000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,51.600000,516.00000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,76.225000,762.25000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,99.900000,999.00000,NaN

In [ ]:
registration_df.describe(include="all")

,Unnamed: 0,State Name,Two Wheeler,Three Wheeler,Four Wheeler,Goods Vehicles,Public Service Vehicle,Special Category Vehicles,Ambulance/Hearses,Construction Equipment Vehicle,Other,Grand Total,total-charging-stations
count,32.000000,32,32.000000,32.000000,32.00000,32.000000,32.000000,32.00000,32.000000,32.000000,32.000000,32.000000,24.000000
unique,NaN,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Andaman and Nicobar Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,15.500000,NaN,8829.437500,20224.562500,822.96875,94.875000,63.718750,12.81250,0.187500,12.406250,137.875000,30198.843750,57.666667
std,9.380832,NaN,15027.420445,49311.798762,1661.50339,287.596912,161.503467,60.76047,0.470929,65.050283,377.119879,54220.859227,69.800752
min,0.000000,NaN,1.000000,0.000000,2.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,20.000000,1.000000
25%,7.750000,NaN,68.500000,31.500000,13.75000,1.750000,0.750000,0.00000,0.000000,0.000000,1.000000,1323.000000,7.750000
50%,15.500000,NaN,1984.500000,1992.000000,131.50000,10.000000,12.500000,0.00000,0.000000,0.000000,11.000000,11156.500000,25.000000
75%,23.250000,NaN,10306.500000,17007.250000,638.50000,31.250000,40.000000,1.00000,0.000000,0.000000,58.000000,45205.000000,80.250000
max,31.000000,NaN,56737.000000,257159.000000,7212.00000,1281.000000,851.000000,344.00000,2.000000,368.000000,1602.000000,276217.000000,265.000000

In [ ]:
population_df.describe(include="all")

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,literates_total,literates_male,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
count,493,493.000000,493,493.000000,4.930000e+02,4.930000e+02,4.930000e+02,4.930000e+02,493.000000,493.000000,4.930000e+02,4.930000e+02,4.930000e+02,493.000000,493.000000,493.000000,493.000000,493.000000,493,4.930000e+02,4.930000e+02,4.930000e+02
unique,492,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,490,NaN,NaN,NaN
top,Aurangabad,NaN,UTTAR PRADESH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"22.6500518,88.3423199",NaN,NaN,NaN
freq,2,NaN,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
mean,NaN,18.643002,NaN,16.782961,4.481124e+05,2.343468e+05,2.137656e+05,4.709285e+04,24849.527383,22243.320487,3.461527e+05,1.894384e+05,1.567143e+05,930.294118,902.332657,85.131460,89.920162,79.967181,NaN,6.620236e+04,3.771556e+04,2.848680e+04
std,NaN,9.297168,NaN,15.566131,1.033228e+06,5.487786e+05,4.848622e+05,1.050279e+05,55535.310272,49523.241379,8.220952e+05,4.534753e+05,3.690677e+05,55.849106,49.794689,6.186345,5.377492,7.577825,NaN,1.778187e+05,9.849574e+04,7.951556e+04
min,NaN,1.000000,NaN,1.000000,1.000360e+05,5.020100e+04,4.512600e+04,6.547000e+03,3406.000000,3107.000000,5.699800e+04,3.475100e+04,2.224700e+04,700.000000,762.000000,49.510000,52.270000,46.450000,NaN,2.532000e+03,1.703000e+03,8.290000e+02
25%,NaN,9.000000,NaN,7.000000,1.261420e+05,6.638400e+04,6.041100e+04,1.363900e+04,7221.000000,6457.000000,9.768700e+04,5.357800e+04,4.391400e+04,890.000000,868.000000,81.750000,87.280000,75.800000,NaN,1.527700e+04,9.289000e+03,6.114000e+03
50%,NaN,19.000000,NaN,13.000000,1.841330e+05,9.665500e+04,8.776800e+04,1.944000e+04,10342.000000,9172.000000,1.413290e+05,7.590600e+04,6.383600e+04,922.000000,903.000000,85.970000,91.180000,80.920000,NaN,2.395900e+04,1.404900e+04,9.558000e+03
75%,NaN,27.000000,NaN,21.000000,3.490330e+05,1.750550e+05,1.700260e+05,3.794500e+04,19982.000000,17954.000000,2.679000e+05,1.455480e+05,1.235030e+05,971.000000,942.000000,89.330000,93.400000,85.400000,NaN,5.036700e+04,2.787200e+04,2.086600e+04
max,NaN,35.000000,NaN,99.000000,1.247845e+07,6.736815e+06,5.741632e+06,1.209275e+06,647938.000000,561337.000000,1.023759e+07,5.727774e+06,4.509812e+06,1093.000000,1185.000000,98.800000,99.300000,98.310000,NaN,2.221137e+06,1.210040e+06,1.011097e+06

## Initial Observations

- All four datasets have been successfully loaded.
- The datasets represent different aspects of the EV ecosystem.
- Some datasets contain categorical variables while others contain numerical variables.
- Further preprocessing is required before merging the datasets.
- The next step is Data Understanding and Data Quality Assessment.

## Conclusion

All required datasets were successfully imported into the project environment.

The datasets will be explored in detail in the next notebook to understand their structure, identify data quality issues, and determine the columns required for machine learning and business analytics.