# EV Charging Infrastructure Planning & Demand Prediction

## Notebook 06 : Master Dataset Creation

### Business Objective

The objective of this notebook is to merge all cleaned datasets into a single master dataset. This master dataset will be used for exploratory data analysis, feature engineering, machine learning model development, and dashboard creation.

In [68]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [69]:
# ==========================================================
# Load Cleaned Datasets
# ==========================================================

population = pd.read_csv("../data/processed/population_clean.csv")

ev = pd.read_csv("../data/processed/ev_registration_clean.csv")

station_master = pd.read_csv("../data/processed/station_master_clean.csv")

station_usage = pd.read_csv("../data/processed/station_usage_clean.csv")

charging = pd.read_csv("../data/processed/charging_stations_clean.csv")

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [70]:
print("Population :", population.shape)
print("EV Registration :", ev.shape)
print("Station Master :", station_master.shape)
print("Station Usage :", station_usage.shape)
print("Charging Stations :", charging.shape)

Population : (580, 4)
EV Registration : (4500, 11)
Station Master : (129, 24)
Station Usage : (7740, 18)
Charging Stations : (380, 10)

In [71]:
station_master_city = (
    station_master
    .groupby(["State", "City"], as_index=False)
    .agg({
        "Total_Chargers": "sum",
        "AC_Chargers": "sum",
        "DC_Chargers": "sum",
        "Fast_Chargers": "sum",
        "Parking_Capacity": "sum",
        "Nearby_EV_Population": "mean"
    })
)

In [72]:
station_usage_city = (
    station_usage
    .merge(
        station_master[["Station_ID", "State", "City"]],
        on="Station_ID",
        how="left"
    )
    .groupby(["Year", "Month", "State", "City"], as_index=False)
    .agg({
        "Avg_Daily_Users": "sum",
        "Peak_Hour_Users": "sum",
        "Avg_Wait_Time_Min": "mean",
        "Avg_Charging_Time_Min": "mean",
        "Queue_Length": "sum",
        "Energy_Delivered_kWh": "sum",
        "Sessions": "sum",
        "Completed_Sessions": "sum",
        "Cancelled_Sessions": "sum",
        "Revenue_INR": "sum",
        "Fault_Count": "sum",
        "Downtime_Hours": "sum",
        "Customer_Rating": "mean"
    })
)

In [73]:
master = pd.merge(
    population,
    ev,
    on=["Year","State","City"],
    how="left"
)

print(master.shape)

(4540, 12)

In [74]:
master = pd.merge(
    master,
    charging,
    on=["Year","State","City"],
    how="left"
)

print(master.shape)

(4540, 19)

In [75]:
master = pd.merge(
    master,
    station_master,
    on=["State","City"],
    how="left"
)

print(master.shape)

(9955, 41)

In [76]:
master = pd.merge(
    master,
    station_usage,
    on=["Station_ID", "Year", "Month"],
    how="left"
)

In [77]:
print(master.info())

<class 'pandas.DataFrame'>
RangeIndex: 9955 entries, 0 to 9954
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     9955 non-null   int64
 1   State                    9955 non-null   str
 2   City                     9955 non-null   str
 3   Population               9955 non-null   int64
 4   Month                    9720 non-null   str
 5   Month_No                 9720 non-null   float64
 6   2W                       9720 non-null   float64
 7   3W                       9720 non-null   float64
 8   4W                       9720 non-null   float64
 9   Bus                      9720 non-null   float64
 10  Goods                    9720 non-null   float64
 11  Total_EV                 9720 non-null   float64
 12  Public_AC                8600 non-null   float64
 13  Public_DC                8600 non-null   float64
 14  Private                  8600 non-null   float64
 15  Highway_Fast             8600 non-null   float64
 16  Total_Charging_Stations  8600 non-null   float64
 17  Utilization_%_x          8600 non-null   float64
 18  Avg_Daily_Sessions       8600 non-null   float64
 19  Station_ID               7340 non-null   str
 20  Station_Name             7340 non-null   str
 21  Latitude                 7340 non-null   float64
 22  Longitude                7340 non-null   float64
 23  Station_Type             7340 non-null   str
 24  Operator                 7340 non-null   str
 25  Charger_Type             7340 non-null   str
 26  Total_Chargers           7340 non-null   float64
 27  AC_Chargers              7340 non-null   float64
 28  DC_Chargers              7340 non-null   float64
 29  Fast_Chargers            7340 non-null   float64
 30  Installation_Year        7340 non-null   float64
 31  Parking_Capacity         7340 non-null   float64
 32  Nearby_Highway           7340 non-null   str
 33  Nearby_Mall              7340 non-null   str
 34  Nearby_Hospital          7340 non-null   str
 35  Nearby_EV_Population     7340 non-null   float64
 36  Status                   7340 non-null   str
 37  Fast_Charger_Ratio       7340 non-null   float64
 38  DC_Ratio                 7340 non-null   float64
 39  Station_Age              7340 non-null   float64
 40  Utilization_Level        7340 non-null   str
 41  Avg_Daily_Users          7320 non-null   float64
 42  Peak_Hour_Users          7320 non-null   float64
 43  Avg_Wait_Time_Min        7320 non-null   float64
 44  Avg_Charging_Time_Min    7320 non-null   float64
 45  Queue_Length             7320 non-null   float64
 46  Energy_Delivered_kWh     7320 non-null   float64
 47  Utilization_%_y          7320 non-null   float64
 48  Fault_Count              7320 non-null   float64
 49  Downtime_Hours           7320 non-null   float64
 50  Revenue_INR              7320 non-null   float64
 51  Customer_Rating          7320 non-null   float64
 52  Sessions                 7320 non-null   float64
 53  Completed_Sessions       7320 non-null   float64
 54  Cancelled_Sessions       7320 non-null   float64
 55  Demand_Level             7320 non-null   str
dtypes: float64(40), int64(2), str(14)
memory usage: 4.9 MB
None

In [78]:
print(master.isnull().sum())

Year                          0
State                         0
City                          0
Population                    0
Month                       235
Month_No                    235
2W                          235
3W                          235
4W                          235
Bus                         235
Goods                       235
Total_EV                    235
Public_AC                  1355
Public_DC                  1355
Private                    1355
Highway_Fast               1355
Total_Charging_Stations    1355
Utilization_%_x            1355
Avg_Daily_Sessions         1355
Station_ID                 2615
Station_Name               2615
Latitude                   2615
Longitude                  2615
Station_Type               2615
Operator                   2615
Charger_Type               2615
Total_Chargers             2615
AC_Chargers                2615
DC_Chargers                2615
Fast_Chargers              2615
Installation_Year          2615
Parking_Capacity           2615
Nearby_Highway             2615
Nearby_Mall                2615
Nearby_Hospital            2615
Nearby_EV_Population       2615
Status                     2615
Fast_Charger_Ratio         2615
DC_Ratio                   2615
Station_Age                2615
Utilization_Level          2615
Avg_Daily_Users            2635
Peak_Hour_Users            2635
Avg_Wait_Time_Min          2635
Avg_Charging_Time_Min      2635
Queue_Length               2635
Energy_Delivered_kWh       2635
Utilization_%_y            2635
Fault_Count                2635
Downtime_Hours             2635
Revenue_INR                2635
Customer_Rating            2635
Sessions                   2635
Completed_Sessions         2635
Cancelled_Sessions         2635
Demand_Level               2635
dtype: int64

In [79]:
print(master.duplicated().sum())

0

In [80]:
master.head()

,Year,State,City,Population,Month,Month_No,2W,3W,4W,Bus,Goods,Total_EV,Public_AC,Public_DC,Private,Highway_Fast,Total_Charging_Stations,Utilization_%_x,Avg_Daily_Sessions,Station_ID,Station_Name,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status,Fast_Charger_Ratio,DC_Ratio,Station_Age,Utilization_Level,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Utilization_%_y,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level
0,2021,Andhra Pradesh,Visakhapatnam,2287676,January,1.0,961.0,180.0,135.0,12.0,54.0,1342.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,Andhra Pradesh,Visakhapatnam,2287676,February,2.0,1115.0,209.0,156.0,13.0,62.0,1555.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,Andhra Pradesh,Visakhapatnam,2287676,March,3.0,1142.0,214.0,160.0,14.0,64.0,1594.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Andhra Pradesh,Visakhapatnam,2287676,April,4.0,1131.0,212.0,159.0,14.0,63.0,1579.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Andhra Pradesh,Visakhapatnam,2287676,May,5.0,1093.0,205.0,153.0,13.0,61.0,1525.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
# master.rename(columns={"Year_x":"Year"}, inplace=True)

# master.drop(columns=["Year_y"], inplace=True)

In [82]:
# master.rename(columns={"Month_x":"Month"}, inplace=True)

# master.drop(columns=["Month_y"], inplace=True)

In [83]:
master.rename(columns={
    "Utilization_%_x":"Station_Utilization",
    "Utilization_%_y":"Usage_Utilization"
}, inplace=True)

In [84]:
print(population.shape)

print(ev.shape)

print(charging.shape)

print(station_master.shape)

print(station_usage.shape)

(580, 4)
(4500, 11)
(380, 10)
(129, 24)
(7740, 18)

In [85]:
master.shape

(9955, 56)

In [86]:
print(master.isnull().sum())

Year                          0
State                         0
City                          0
Population                    0
Month                       235
Month_No                    235
2W                          235
3W                          235
4W                          235
Bus                         235
Goods                       235
Total_EV                    235
Public_AC                  1355
Public_DC                  1355
Private                    1355
Highway_Fast               1355
Total_Charging_Stations    1355
Station_Utilization        1355
Avg_Daily_Sessions         1355
Station_ID                 2615
Station_Name               2615
Latitude                   2615
Longitude                  2615
Station_Type               2615
Operator                   2615
Charger_Type               2615
Total_Chargers             2615
AC_Chargers                2615
DC_Chargers                2615
Fast_Chargers              2615
Installation_Year          2615
Parking_Capacity           2615
Nearby_Highway             2615
Nearby_Mall                2615
Nearby_Hospital            2615
Nearby_EV_Population       2615
Status                     2615
Fast_Charger_Ratio         2615
DC_Ratio                   2615
Station_Age                2615
Utilization_Level          2615
Avg_Daily_Users            2635
Peak_Hour_Users            2635
Avg_Wait_Time_Min          2635
Avg_Charging_Time_Min      2635
Queue_Length               2635
Energy_Delivered_kWh       2635
Usage_Utilization          2635
Fault_Count                2635
Downtime_Hours             2635
Revenue_INR                2635
Customer_Rating            2635
Sessions                   2635
Completed_Sessions         2635
Cancelled_Sessions         2635
Demand_Level               2635
dtype: int64

In [87]:
print("Duplicate Rows :", master.duplicated().sum())

Duplicate Rows : 0

In [88]:
print(master.dtypes)

Year                         int64
State                          str
City                           str
Population                   int64
Month                          str
Month_No                   float64
2W                         float64
3W                         float64
4W                         float64
Bus                        float64
Goods                      float64
Total_EV                   float64
Public_AC                  float64
Public_DC                  float64
Private                    float64
Highway_Fast               float64
Total_Charging_Stations    float64
Station_Utilization        float64
Avg_Daily_Sessions         float64
Station_ID                     str
Station_Name                   str
Latitude                   float64
Longitude                  float64
Station_Type                   str
Operator                       str
Charger_Type                   str
Total_Chargers             float64
AC_Chargers                float64
DC_Chargers                float64
Fast_Chargers              float64
Installation_Year          float64
Parking_Capacity           float64
Nearby_Highway                 str
Nearby_Mall                    str
Nearby_Hospital                str
Nearby_EV_Population       float64
Status                         str
Fast_Charger_Ratio         float64
DC_Ratio                   float64
Station_Age                float64
Utilization_Level              str
Avg_Daily_Users            float64
Peak_Hour_Users            float64
Avg_Wait_Time_Min          float64
Avg_Charging_Time_Min      float64
Queue_Length               float64
Energy_Delivered_kWh       float64
Usage_Utilization          float64
Fault_Count                float64
Downtime_Hours             float64
Revenue_INR                float64
Customer_Rating            float64
Sessions                   float64
Completed_Sessions         float64
Cancelled_Sessions         float64
Demand_Level                   str
dtype: object

In [89]:
print(master.columns.tolist())

['Year', 'State', 'City', 'Population', 'Month', 'Month_No', '2W', '3W', '4W', 'Bus', 'Goods', 'Total_EV', 'Public_AC', 'Public_DC', 'Private', 'Highway_Fast', 'Total_Charging_Stations', 'Station_Utilization', 'Avg_Daily_Sessions', 'Station_ID', 'Station_Name', 'Latitude', 'Longitude', 'Station_Type', 'Operator', 'Charger_Type', 'Total_Chargers', 'AC_Chargers', 'DC_Chargers', 'Fast_Chargers', 'Installation_Year', 'Parking_Capacity', 'Nearby_Highway', 'Nearby_Mall', 'Nearby_Hospital', 'Nearby_EV_Population', 'Status', 'Fast_Charger_Ratio', 'DC_Ratio', 'Station_Age', 'Utilization_Level', 'Avg_Daily_Users', 'Peak_Hour_Users', 'Avg_Wait_Time_Min', 'Avg_Charging_Time_Min', 'Queue_Length', 'Energy_Delivered_kWh', 'Usage_Utilization', 'Fault_Count', 'Downtime_Hours', 'Revenue_INR', 'Customer_Rating', 'Sessions', 'Completed_Sessions', 'Cancelled_Sessions', 'Demand_Level']

In [90]:
# Rename Columns
master.rename(columns={
    "Utilization_%_x":"Station_Utilization",
    "Utilization_%_y":"Usage_Utilization"
}, inplace=True)

# Drop unwanted duplicate columns
master.drop(
    columns=["Year_y","Month_y"],
    errors="ignore",
    inplace=True
)

master.rename(columns={
    "Year_x":"Year",
    "Month_x":"Month"
}, inplace=True)

In [91]:
print("Shape :", master.shape)

print("Duplicates :", master.duplicated().sum())

print("Missing Values")
print(master.isnull().sum())

master.info()

master.head()

Shape : (9955, 56)
Duplicates : 0
Missing Values
Year                          0
State                         0
City                          0
Population                    0
Month                       235
Month_No                    235
2W                          235
3W                          235
4W                          235
Bus                         235
Goods                       235
Total_EV                    235
Public_AC                  1355
Public_DC                  1355
Private                    1355
Highway_Fast               1355
Total_Charging_Stations    1355
Station_Utilization        1355
Avg_Daily_Sessions         1355
Station_ID                 2615
Station_Name               2615
Latitude                   2615
Longitude                  2615
Station_Type               2615
Operator                   2615
Charger_Type               2615
Total_Chargers             2615
AC_Chargers                2615
DC_Chargers                2615
Fast_Chargers              2615
Installation_Year          2615
Parking_Capacity           2615
Nearby_Highway             2615
Nearby_Mall                2615
Nearby_Hospital            2615
Nearby_EV_Population       2615
Status                     2615
Fast_Charger_Ratio         2615
DC_Ratio                   2615
Station_Age                2615
Utilization_Level          2615
Avg_Daily_Users            2635
Peak_Hour_Users            2635
Avg_Wait_Time_Min          2635
Avg_Charging_Time_Min      2635
Queue_Length               2635
Energy_Delivered_kWh       2635
Usage_Utilization          2635
Fault_Count                2635
Downtime_Hours             2635
Revenue_INR                2635
Customer_Rating            2635
Sessions                   2635
Completed_Sessions         2635
Cancelled_Sessions         2635
Demand_Level               2635
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 9955 entries, 0 to 9954
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     9955 non-null   int64
 1   State                    9955 non-null   str
 2   City                     9955 non-null   str
 3   Population               9955 non-null   int64
 4   Month                    9720 non-null   str
 5   Month_No                 9720 non-null   float64
 6   2W                       9720 non-null   float64
 7   3W                       9720 non-null   float64
 8   4W                       9720 non-null   float64
 9   Bus                      9720 non-null   float64
 10  Goods                    9720 non-null   float64
 11  Total_EV                 9720 non-null   float64
 12  Public_AC                8600 non-null   float64
 13  Public_DC                8600 non-null   float64
 14  Private                  8600 non-null   float64
 15  Highway_Fast             8600 non-null   float64
 16  Total_Charging_Stations  8600 non-null   float64
 17  Station_Utilization      8600 non-null   float64
 18  Avg_Daily_Sessions       8600 non-null   float64
 19  Station_ID               7340 non-null   str
 20  Station_Name             7340 non-null   str
 21  Latitude                 7340 non-null   float64
 22  Longitude                7340 non-null   float64
 23  Station_Type             7340 non-null   str
 24  Operator                 7340 non-null   str
 25  Charger_Type             7340 non-null   str
 26  Total_Chargers           7340 non-null   float64
 27  AC_Chargers              7340 non-null   float64
 28  DC_Chargers              7340 non-null   float64
 29  Fast_Chargers            7340 non-null   float64
 30  Installation_Year        7340 non-null   float64
 31  Parking_Capacity         7340 non-null   float64
 32  Nearby_Highway           7340 non-null   str
 33  Nearby_Mall              7340 non-null   str
 34  Nearby_Hospital          7340 non-null   str
 35  Nearby_EV_Population     7340 non-null   float64
 36  Status                   7340 non-null   str
 37  Fast_Charger_Ratio       7340 non-null   float64
 38  DC_Ratio                 7340 non-null   float64
 39  Station_Age              7340 non-null   float64
 40  Utilization_Level        7340 non-null   str
 41  Avg_Daily_Users          7320 non-null   float64
 42  Peak_Hour_Users          7320 non-null   float64
 43  Avg_Wait_Time_Min        7320 non-null   float64
 44  Avg_Charging_Time_Min    7320 non-null   float64
 45  Queue_Length             7320 non-null   float64
 46  Energy_Delivered_kWh     7320 non-null   float64
 47  Usage_Utilization        7320 non-null   float64
 48  Fault_Count              7320 non-null   float64
 49  Downtime_Hours           7320 non-null   float64
 50  Revenue_INR              7320 non-null   float64
 51  Customer_Rating          7320 non-null   float64
 52  Sessions                 7320 non-null   float64
 53  Completed_Sessions       7320 non-null   float64
 54  Cancelled_Sessions       7320 non-null   float64
 55  Demand_Level             7320 non-null   str
dtypes: float64(40), int64(2), str(14)
memory usage: 4.9 MB

,Year,State,City,Population,Month,Month_No,2W,3W,4W,Bus,Goods,Total_EV,Public_AC,Public_DC,Private,Highway_Fast,Total_Charging_Stations,Station_Utilization,Avg_Daily_Sessions,Station_ID,Station_Name,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status,Fast_Charger_Ratio,DC_Ratio,Station_Age,Utilization_Level,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Usage_Utilization,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level
0,2021,Andhra Pradesh,Visakhapatnam,2287676,January,1.0,961.0,180.0,135.0,12.0,54.0,1342.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,Andhra Pradesh,Visakhapatnam,2287676,February,2.0,1115.0,209.0,156.0,13.0,62.0,1555.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,Andhra Pradesh,Visakhapatnam,2287676,March,3.0,1142.0,214.0,160.0,14.0,64.0,1594.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Andhra Pradesh,Visakhapatnam,2287676,April,4.0,1131.0,212.0,159.0,14.0,63.0,1579.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Andhra Pradesh,Visakhapatnam,2287676,May,5.0,1093.0,205.0,153.0,13.0,61.0,1525.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
master.to_csv(
    "../data/processed/master_dataset.csv",
    index=False
)

print("Master Dataset Saved Successfully.")

Master Dataset Saved Successfully.

In [93]:
master.to_csv("../data/processed/master_dataset.csv", index=False)

master = pd.read_csv("../data/processed/master_dataset.csv")